### PR TITLE
Call "merge-release.js" directly, rather than deploying as npm package

### PR DESCRIPTION
**Pull request by benwinding**
Hi @mikeal,
This relates to issue #22 . But here's a brief overview of this PR

### Current System
- Currently this repository is also published to npm as https://www.npmjs.com/package/merge-release 
- The `merge-release.js` script is executed using `npx` in `entrypoint.sh`, which runs the package + install dependencies from npm
https://github.com/mikeal/merge-release/blob/69d0bc4750a97ce4e1c81d4a7c86088f79bd051d/entrypoint.sh#L44
This means that each fork of this action, also needs to deploy their own package to npm too, which is not ideal for people to add improvements.

### Proposed Changes (this PR)
- Moved `package.json` and `merge-release.js` into a `src` directory.
- In the Dockerfile we copy the `./src` directory into the docker image and install the dependencies there (at build time)
- The script is executed using `node` in `entrypoint.sh` (as all dependencies are already there), rather than downloading the npm package `merge-release`

https://github.com/benwinding/merge-release/blob/87f0410e7678aa4dd12c76c1c9569d4f9f29eb9f/entrypoint.sh#L39-L40

- `.dockerignore` file added for convenience of which files are copied into the image
- `action.yaml` file added for the action's metadata (inputs/outputs) [more info here](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions)

### Conclusion
- Try out the action on my fork `uses: benwinding/merge-release@87f0410e7678aa4dd12c76c1c9569d4f9f29eb9f`
- This makes https://www.npmjs.com/package/merge-release redundant and not required anymore.
- Anyone who forks this project can make a change and test it on their fork very easily (rather than requiring an npm package)

### Future Improvements
- Using this same method, you could deploy an image to docker hub (which includes all dependencies already downloaded) this would probably make the image 80% faster as no `apt-get` or `npm` dependencies will be downloaded at each github action run. 

Let me know if there's any questions, concerns or changes you think are necessary.

Cheers,
Ben

### CODE REVIEW

**Comment by mikeal** [comment]
Love it!

Moving the `package.json` appears to have broken the tests and probably the publish phase of this repo though.

I’m a little conflicted about how to fix that though. Now that we aren’t calling `npx` we don’t actually need the publish to npm phase (I would like some level or testing or linting in the project though) so we could dump that entire workflow and do something new that just pushed taged releases for every push that passes some linting.

Thoughts? I don’t want to derail this improvement with a bunch of build tooling so let me know what sounds easiest and we’ll go with that for now.

**Comment by mikeal** [comment]
Would love to get this in ;)

**Comment by benwinding** [comment]
> Would love to get this in ;)

Me too! :grinning:  

I just added another commit, which changes the `mikeals-workflow.yml` file:
- Fixes tests (by specifying new `working-directory`)
- Changes the publish build-step to use the action [rymndhng/release-on-push-action](https://github.com/rymndhng/release-on-push-action), there might be a better action/method for this, but I'm not sure.

Cheers,
Ben

**Comment by mikeal** [comment]
Looks good, merging.

**Pull request merged**
